version: '3.8'

services:
  eduetor-frontend:
    build: .
    container_name: eduetor-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - eduetor-network
    environment:
      - NODE_ENV=production
    volumes:
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add a database service if needed
  # eduetor-db:
  #   image: postgres:15-alpine
  #   container_name: eduetor-db
  #   environment:
  #     POSTGRES_DB: eduetor
  #     POSTGRES_USER: eduetor
  #     POSTGRES_PASSWORD: your-password
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - eduetor-network

networks:
  eduetor-network:
    driver: bridge

volumes:
  nginx-logs:
  # postgres-data:  # Uncomment if using database
